pipeline {

    agent any

    environment {
        IMAGE_NAME = "rameshbaskaran/employee-api"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Code Quality - SonarQube') {
            steps {
                script {

                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('SonarQube') {

                        dir('Kubernetes/employee-api') {

                            bat """
                            "${scannerHome}\\bin\\sonar-scanner.bat"
                            """

                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {

                dir('Kubernetes/employee-api') {

                    bat """
                    docker build -t %IMAGE_NAME%:%IMAGE_TAG% .
                    """

                }

            }
        }

        stage('Verify Docker Image') {
            steps {

                bat """
                docker images
                """

            }
        }

        stage('Trivy Image Scan') {
            steps {

                bat """
                trivy image --format table --output trivy-report.txt %IMAGE_NAME%:%IMAGE_TAG%
                type trivy-report.txt
                """

            }
        }

        stage('Push Docker Image') {
    steps {

        withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )
        ]) {

            bat """
            echo Logging into Docker Hub as %DOCKER_USER%

            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin

            docker images

            docker push %IMAGE_NAME%:%IMAGE_TAG%

            docker logout
            """

        }
    }
}

        stage('Update Helm values.yaml') {
            steps {

                dir('Kubernetes/employee-api-chart') {

                    bat """
                    powershell -Command "(Get-Content values.yaml) -replace 'tag: \\".*\\"','tag: \\"%IMAGE_TAG%\\"' | Set-Content values.yaml"

                    echo ====================================
                    echo Updated values.yaml
                    echo ====================================

                    type values.yaml
                    """

                }

            }
        }

        stage('Commit & Push Helm Chart') {
    steps {

        withCredentials([
            usernamePassword(
                credentialsId: 'github-creds',
                usernameVariable: 'GIT_USER',
                passwordVariable: 'GIT_PASS'
            )
        ]) {

            bat """
            git config user.name "Jenkins"
            git config user.email "jenkins@local"

            git add Kubernetes/employee-api-chart/values.yaml

            git commit -m "Update image tag to %IMAGE_TAG%" || echo No changes to commit

            git push https://%GIT_USER%:%GIT_PASS%@github.com/RameshkumarBaskaran/DevOps-Projects.git HEAD:main
            """

        }
    }
}

        stage('GitOps Verification') {
            steps {

                echo "======================================="
                echo "GitHub repository updated successfully."
                echo "Argo CD should detect the new commit."
                echo "Watch Argo CD:"
                echo "Healthy -> OutOfSync -> Syncing -> Healthy"
                echo "======================================="

            }
        }

    }

    post {

        success {

            echo "========================================="
            echo "Pipeline Executed Successfully"
            echo "Docker Image : ${IMAGE_NAME}:${IMAGE_TAG}"
            echo "Helm Chart Updated"
            echo "GitHub Updated"
            echo "Waiting for Argo CD Sync"
            echo "========================================="

        }

        failure {

            echo "========================================="
            echo "Pipeline Failed"
            echo "Check Jenkins Console Output"
            echo "========================================="

        }

        always {

            archiveArtifacts artifacts: 'trivy-report.txt', allowEmptyArchive: true
            cleanWs()

        }

    }

}