pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('AWS-Landing-Zone') {
                    bat 'terraform init'
                }
            }
        }

        stage('Terraform Format') {
            steps {
                dir('AWS-Landing-Zone') {
                    bat 'terraform fmt -check -recursive'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('AWS-Landing-Zone') {
                    bat 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('AWS-Landing-Zone') {
                    bat 'terraform plan -out=tfplan'
                }
            }
        }

    }
}