name: Terraform CI

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "AWS-Landing-Zone/**"
      - ".github/workflows/terraform-ci.yml"

  push:
    branches:
      - main
    paths:
      - "AWS-Landing-Zone/**"
      - ".github/workflows/terraform-ci.yml"

permissions:
  contents: read

env:
  TF_VERSION: "1.13.1"
  TF_WORKING_DIR: "AWS-Landing-Zone"

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
